services:
  - type: web
    name: wackker-gallery
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_APP_ID
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
